spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
---
spring:
  main:
    allow-circular-references: true
---
spring:
 data:
   web:
     pageable:
       default-page-size: 10
       max-page-size: 100
 profiles:
   active:
     - dev
 servlet:
   multipart:
     max-file-size: 10MB
#     - production
#hoaxify:
#  upload-path: picture-storage
---
spring:
  profiles: production
hoaxify:
  upload-path: storage-production
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:./dev-db
  jpa:
    hibernate:
      ddl-auto: update
hoaxify:
  upload-path: storage-dev


---
#spring:
#  jackson:
#    mapper:
#     DEFAULT_VIEW_INCLUSION: true